# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca4db8a1081684dcaaea4e16c9ad540a3a42763b598b0ac5f44bf0292baee48b1e4e21d0edaa93d4e47bc757bcef965089d4957953451d126339cf957ac63827
  thrusted_ip: '77.253.40.19'
test:
  secret_key_base: dc5673349b422af6f191575072918f9c2370793620f228d8e4734d2f6f42cde28944dbefc3acc60d58ca3a24faae4cae122edf53a6e26c6c4ad9c349eaa1d217

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
